# some more ls aliases
alias ll='ls -AlhF --sort=extension'
alias l='ls -CF'
alias cp='cp -i'
alias e='exit'
alias c='clear'
alias fy='dict -d langdao-ec'
alias fyy='dict -d langdao-ce'
alias how='tldr'
alias startconda='source /opt/anaconda/bin/activate root'
alias stopconda='conda deactivate'
