alias l="ls -CF"
alias ll="ls -alhF"
alias cp="/bin/cp -i -r"
alias e="exit"
alias c="clear"
alias ra="ranger"
alias dk="docker"
alias rsync="rsync -avhP"

alias gst="git status"
alias ga="git add"
alias gc="git-cz c"
alias gp="git push"
alias gl="git pull"

alias fy="dict -d langdao-ec"
alias fyy="dict -d langdao-ce"
alias how="tldr"
alias texrm="~/.scripts/rmtexfiles.sh"
alias er="~/.scripts/cnyhkd.sh"
alias boc="~/.scripts/boc.sh"
alias tx="~/.scripts/tx.sh"
alias clipdict="~/.scripts/ClipDict.sh"
alias gbk2utf="~/.scripts/GBK2UTF8.sh"
